### ISSUE TITLE
gke-gcloud: give a user more flexibility to choose GKE release channel and minor versions

### ISSUE THREAD

**Issue by oginskis** [agilestacks/google-stacks#2]
I, as a Google support engineer, when deploying the GKE cluster should be able to choose the release channel and also a minor version of the GKE cluster (such as 1.23.5-gke.1503, or similar)

https://cloud.google.com/sdk/gcloud/reference/container/clusters/create#--release-channel

- [x]  `gke-gcloud` component must be updated to support that

**Comment by TheRealSpaceShip** [comment]
Done via custom configure script.
